{{- if index .Values.services.live "hpa" "enabled" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-live
  namespace: {{ .Release.Namespace }}
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-live
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-live
  minReplicas: {{ .Values.services.live.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.services.live.hpa.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.live.hpa.targetCPUUtilizationPercentage | default 80 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.live.hpa.targetMemoryUtilizationPercentage | default 80 }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
{{- end }}
