{{- if .Values.services.pi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-pi-beat-wl
  {{- include "plane.labelsAndAnnotations" .Values.services.pi_beat_worker }}
spec:
  replicas: {{ .Values.services.pi_beat_worker.replicas | default 1}}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-pi-beat
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-pi-beat
      annotations:
        timestamp: {{ now | quote }}
    spec:
      {{- include "plane.podScheduling" .Values.services.pi_beat_worker }}
      {{- with (include "plane.s3CAVolumes" .) }}
{{ . | indent 6 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-pi-beat
        imagePullPolicy: Always
        image: {{ .Values.services.pi.image | default "artifacts.plane.so/makeplane/plane-pi-commercial" }}:{{ .Values.planeVersion }}
        stdin: true
        tty: true
        resources:
          requests:
            memory: {{ .Values.services.pi_beat_worker.memoryRequest | default "1000Mi" | quote }}
            cpu: {{ .Values.services.pi_beat_worker.cpuRequest | default "500m" | quote}}
          limits:
            memory: {{ .Values.services.pi_beat_worker.memoryLimit | default "1000Mi" | quote }}
            cpu: {{ .Values.services.pi_beat_worker.cpuLimit | default "500m" | quote}}
        {{- with (include "plane.s3CAVolumeMounts" .) }}
{{ . | indent 8 }}
        {{- end }}
        command:
          - /bin/bash
          - -c
          - |
            set -e
            {{- with (include "plane.s3CAInitScript" .) }}
{{ . | indent 12 }}
            {{- end }}

            exec ./bin/entrypoint-celery-beat.sh
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-pi-api-vars
              optional: false
          - secretRef:
              name: {{ if not (empty .Values.external_secrets.pi_api_env_existingSecret) }}{{ .Values.external_secrets.pi_api_env_existingSecret }}{{ else }}{{ .Release.Name }}-pi-api-secrets{{ end }}
              optional: false
          - secretRef:
              name: {{ if not (empty .Values.external_secrets.doc_store_existingSecret) }}{{ .Values.external_secrets.doc_store_existingSecret }}{{ else }}{{ .Release.Name }}-doc-store-secrets{{ end }}
              optional: false
          - secretRef:
              name: {{ if not (empty .Values.external_secrets.opensearch_existingSecret) }}{{ .Values.external_secrets.opensearch_existingSecret }}{{ else }}{{ .Release.Name }}-opensearch-secrets{{ end }}
              optional: false
        {{- if or .Values.extraEnv (include "plane.s3CAEnabled" .) }}
        env:
          {{- with (include "plane.s3CAEnvVars" .) }}
{{ . | indent 10 }}
          {{- end }}
          {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}
        {{- end }}
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
---
{{- end }}
