{{- if .Values.services.redis.local_setup }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-redis
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-redis
spec:
  {{- if not .Values.services.redis.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
  ports:
  - name: redis-{{ .Values.services.redis.servicePort }}
    port: {{ .Values.services.redis.servicePort }}
    protocol: TCP
    targetPort: 6379
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-redis
---

# REDIS WORKLOAD

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-redis-wl
spec:
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-redis
  serviceName:  {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-redis
    spec:
      containers:
      - image: {{ .Values.services.redis.image }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-redis
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /data
          name: pvc-{{ .Release.Name }}-redis-vol
          subPath: ''
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      namespace: {{ .Release.Namespace }}
      name: pvc-{{ .Release.Name }}-redis-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.services.redis.volumeSize | default "1Gi" | quote }}
      storageClassName: {{ .Values.env.storageClass | quote }}
      volumeMode: Filesystem
      
{{- end }}