{{- if .Values.services.runner.enabled }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-runner
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-runner
    {{- include "plane.commonLabels" $ | nindent 4 }}
spec:
  type: ClusterIP
  {{- if not .Values.services.runner.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
  ports:
  - name: runner-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-runner

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-runner-wl
  {{- include "plane.labelsAndAnnotations" (dict "context" $ "values" .Values.services.runner) }}
spec:
  replicas: {{ .Values.services.runner.replicas | default 1}}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-runner
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-runner
        {{- include "plane.commonLabels" $ | nindent 8 }}
      annotations:
        {{- if not $.Values.gitops.enabled }}
        timestamp: {{ now | quote }}
        {{- end }}
    spec:
      {{- include "plane.podScheduling" .Values.services.runner }}
      {{- include "plane.podSecurityContext" . }}
      containers:
      - name: {{ .Release.Name }}-runner
        {{- include "plane.containerSecurityContext" . }}
        imagePullPolicy: {{ .Values.services.runner.pullPolicy | default "Always" }}
        image: {{ .Values.services.runner.image | default "makeplane/node-runner-commercial" }}:{{ .Values.planeVersion }}
        stdin: true
        tty: true
        resources:
          requests:
            memory: {{ .Values.services.runner.memoryRequest | default "128Mi" | quote }}
            cpu: {{ .Values.services.runner.cpuRequest | default "100m" | quote }}
          limits:
            memory: {{ .Values.services.runner.memoryLimit | default "512Mi" | quote }}
            cpu: {{ .Values.services.runner.cpuLimit | default "500m" | quote }}
        readinessProbe:
          tcpSocket:
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-runner-vars
              optional: false
          - secretRef:
              name: {{ if not (empty .Values.external_secrets.runner_env_existingSecret) }}{{ .Values.external_secrets.runner_env_existingSecret }}{{ else }}{{ .Release.Name }}-runner-secrets{{ end }}
              optional: false
        {{- if .Values.extraEnv }}
        env:
          {{- toYaml .Values.extraEnv | nindent 10 }}
        {{- end }}
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account
---
{{- end }}
