
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-web
  labels:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
spec:
  type: ClusterIP
  {{- if not .Values.services.web.assign_cluster_ip }}
  clusterIP: None
  {{- end }}
  ports:
  - name: web-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-web-wl
spec:
  replicas: {{ .Values.services.web.replicas | default 1 }}
  selector:
    matchLabels:
      app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.name: {{ .Release.Namespace }}-{{ .Release.Name }}-web
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}-web
        imagePullPolicy: {{ .Values.services.web.pullPolicy | default "Always" }}
        image: {{ .Values.services.web.image | default "artifacts.plane.so/makeplane/web-commercial" }}:{{ .Values.planeVersion }}
        stdin: true
        tty: true
        resources:
          requests:
            memory: {{ .Values.services.web.memoryRequest | default "50Mi" | quote }}
            cpu: {{ .Values.services.web.cpuRequest | default "50m" | quote }}
          limits:
            memory: {{ .Values.services.web.memoryLimit  | default "1000Mi" | quote }}
            cpu: {{ .Values.services.web.cpuLimit | default "500m" | quote}}
      serviceAccount: {{ .Release.Name }}-srv-account
      serviceAccountName: {{ .Release.Name }}-srv-account

---