{{- if and .Values.services.email_service.enabled .Values.env.email_service_envs.smtp_domain }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-mail-tls-cert
  labels:
    {{- include "plane.resourceLabels" $ | nindent 4 }}
  {{- with (include "plane.resourceAnnotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Values.env.email_service_envs.smtp_domain | quote }}
  
  issuerRef:
    name: {{ .Release.Name }}-cert-issuer
  secretName: {{ .Release.Name }}-mail-tls-secret
--- 
{{- end }}