{{- if and .Values.ingress.enabled (eq .Values.ingress.ingressController "traefik") }}

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-body-limit
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.ingress.traefik.maxRequestBodyBytes | default 10485760 }}

{{- end }}
