{{- $annotations := dict -}}
{{- with .Values.serviceAccount.annotations -}}
{{- $annotations = merge $annotations . -}}
{{- end -}}
{{- with .Values.irsa.annotations -}}
{{- $annotations = merge $annotations . -}}
{{- end -}}
{{- if .Values.irsa.roleArn -}}
{{- $annotations = merge $annotations (dict "eks.amazonaws.com/role-arn" .Values.irsa.roleArn) -}}
{{- end -}}

apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-srv-account
  annotations:
{{ toYaml $annotations | nindent 4 }}
{{- if .Values.dockerRegistry.enabled }}
imagePullSecrets:
{{- if .Values.dockerRegistry.existingSecret }}
  - name: {{ .Values.dockerRegistry.existingSecret }}
{{- else }}
  - name: {{ .Release.Name }}-docker-registry-credentials
{{- end }}
{{- end }}