ingress:
  enabled: true
  host: 'mcp.example.com'
  ingressController: 'traefik' # Allowed: nginx, traefik
  traefik:
    ingressClassName: 'traefik'
    maxRequestBodyBytes: 10485760
    annotations: {}
  nginx:
    ingressClassName: 'nginx'
    annotations: { nginx.ingress.kubernetes.io/proxy-body-size: "10m" }
  ssl:
    enabled: false
    issuer: cloudflare # Allowed : cloudflare, digitalocean, http
    token: '' # not required for http
    server: https://acme-v02.api.letsencrypt.org/directory
    email: engineering@plane.so

services:
  api:
    image: makeplane/plane-mcp-server
    tag: v0.2.11
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    memoryRequest: 50Mi
    cpuRequest: 50m
    plane_base_url: ''
    plane_internal_base_url: ''
    plane_oauth:
      enabled: false
      client_id: ''
      client_secret: ''
      provider_base_url: ''

  redis:
    local_setup: true
    image: valkey/valkey:7.2.11-alpine
    storage_class: ''
    volume_size: 500Mi
    password: '' # sets --requirepass on local Redis and embeds password in REDIS_URL (redis://:password@host:6379/)
    external_redis_url: '' # INCASE OF REMOTE REDIS ONLY
