ingress:
  enabled: true
  host: 'mcp.example.com'
  ingressController: 'traefik' # Allowed: nginx, traefik
  traefik:
    ingressClassName: 'traefik'
    maxRequestBodyBytes: 10485760
    annotations: {}
  nginx:
    ingressClassName: 'nginx'
    annotations: { nginx.ingress.kubernetes.io/proxy-body-size: "10m" }
  ssl:
    enabled: false
    issuer: cloudflare # Allowed : cloudflare, digitalocean, http
    token: '' # not required for http
    server: https://acme-v02.api.letsencrypt.org/directory
    email: engineering@plane.so

services:
  api:
    image: makeplane/plane-mcp-server
    tag: v0.2.11
    replicas: 1
    memoryLimit: 1000Mi
    cpuLimit: 500m
    memoryRequest: 50Mi
    cpuRequest: 50m
    plane_base_url: ''
    plane_internal_base_url: ''
    plane_oauth:
      enabled: false
      client_id: ''
      client_secret: ''
      provider_base_url: ''

valkey:
  local_setup: true
  external_redis_url: '' # used when local_setup is false
  image:
    repository: valkey/valkey
    tag: '9.1.1'
  replica:
    enabled: false  # standalone mode
  auth:
    enabled: false
    aclUsers:
      default:
        permissions: "~* &* +@all"
        password: ''
  dataStorage:
    enabled: false
    className: ''
    requestedSize: '500Mi'
