{{- if .Values.dockerRegistry.enabled }}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-docker-registry-credentials
data:
  .dockerconfigjson: {{ include "plane-mcp-server.imagePullSecret" .}}
type: kubernetes.io/dockerconfigjson

{{- end }}