apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-srv-account
{{- if .Values.dockerRegistry.enabled }}
imagePullSecrets:
  - name: {{ .Release.Name }}-docker-registry-credentials
{{- end}}